#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro package install ffmpeg <args...>"
  echo ""
}

install() {
  which ffmpeg >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    pm install -y ffmpeg
  fi
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  install
  log::success "install ffmpeg success."
}

run() {
  core $@
}

run $@
