#!/bin/bash

set -e

help() {
  echo "Usage:"
  echo "  zmicro package install ffmpeg <args...>"
  echo ""
}

install() {
  pm install -y ffmpeg
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  install
  log::success "install ffmpeg success."
}

run() {
  core $@
}

run $@
